### PR TITLE
WIP: port pylandau to use Numba

### PR DESCRIPTION
**Pull request by leloup314**
This PR ports the pylandau package from using `Cython`-extensions, generated from cpp source code, to architecture-specific, pre-compiled bytecode from pure Python scripts using Numbas Ahead-Of-Time (AOT) compilation capabilities.

All functionality has been ported already, just the package structure needs to be adapted and [Numbas AOT API](https://numba.pydata.org/numba-doc/dev/user/pycc.html) has to be integrated into the package setup.

Performance stays the same:

Cython-based (current) version:

    In [8]: a = np.arange(0, 100, 0.01)

    In [9]: %timeit pylandau.landau(a)
    1.03 ms ± 19.6 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

    In [10]: %timeit pylandau.langau(a)
    19.1 ms ± 15.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

Numba-based version:

    In [13]: a = np.arange(0, 100, 0.01)

    In [14]: %timeit pylandau.landau(a)
    1.02 ms ± 2.17 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)

    In [15]: %timeit pylandau.langau(a)
    17.6 ms ± 24.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

### CODE REVIEW

**Comment by leloup314** [comment]
Test are not expected to succeed due package structure / setup not working yet.

**Comment by leloup314** [comment]
Related to https://github.com/SiLab-Bonn/beam_telescope_analysis/issues/20

**Comment by leloup314** [comment]
@cbespin let's have a chat on how to integrate this

**Comment by cbespin** [comment]
> Related to https://github.com/SiLab-Bonn/beam_telescope_analysis/issues/20

At least this is solve with today's release (coming to pypi tomorrow).

I am always down to get away from cython, we can discuss the details. Changes look good so far

**Comment by leloup314** [comment]
Move development to new branch in this repo

**Pull request closed without merging**
